# Generated by Django 4.2.1 on 2023-05-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advices', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='advice_ye',
        ),
    ]
